services:
  db: 
    image: mysql:8.3
    restart: no
    container_name: mysqldbbdreminder
    ports:
      - 3306:3306
    environment:
      - TZ=Europe/Berlin
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

