/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    war
}

tasks.war {
    archiveFileName.set("birthday-reminder.war")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
    // testImplementation("org.glassfish.jersey.test-framework:jeresy-test-framework-core:3.1.7")

    // This dependency is used by the application.
    implementation("org.apache.logging.log4j:log4j-core:2.21.1")
    implementation("org.flywaydb:flyway-core:10.11.1")
    implementation("org.flywaydb:flyway-mysql:10.11.1")
    implementation("com.mysql:mysql-connector-j:8.1.0")
    // implementation("org.liquibase:liquibase-core:4.26.0")
    
    compileOnly("jakarta.security.enterprise:jakarta.security.enterprise-api:4.0.0")
    compileOnly("jakarta.ws.rs:jakarta.ws.rs-api:3.1.0")
    compileOnly("jakarta.platform:jakarta.jakartaee-api:10.0.0")
    compileOnly("org.eclipse.persistence:eclipselink:4.0.2")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.10.2")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}


tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform{
        excludeTags("IntegrationTest")
    }
}

tasks.register<Test>("integrationTest"){
    description = "Runs integration tests."
    group = "verification"
    useJUnitPlatform{
        includeTags("IntegrationTest")
    }  
}
